apiVersion: v1
kind: Pod
metadata:
  name: seccon3
spec:
# Apply SecurityContext for entire pod
  securityContext:
    runAsUser: 2500
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: security-context-vol
    emptyDir: {}
  containers:
  - name: security-context-cont
    image: ubuntu:latest
    command: ["/bin/sleep", "999999"]
    volumeMounts:
    - name: security-context-vol
      mountPath: /data/test
    securityContext:
      privileged: false
      allowPrivilegeEscalation: true
      capabilities:
        add: 
          - SUID
          - CHOWN